sh_ffj0_position_controller:
  joint: FFJ0
  pid:
    d: 0.005
    i: 0.1
    i_clamp: 0.05
    p: 0.5
    position_deadband: 0.0
    friction_deadband: 0.0
    max_force: 1.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_ffj3_position_controller:
  joint: FFJ3
  pid:
    d: 0.05
    i: 0.2
    i_clamp: 0.2
    p: 1.0
    position_deadband: 0.0
    friction_deadband: 0.0
    max_force: 1.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_ffj4_position_controller:
  joint: FFJ4
  pid:
    d: 0.05
    i: 0.2
    i_clamp: 0.2
    p: 1.0
    position_deadband: 0.0
    friction_deadband: 0.0
    max_force: 1.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_lfj0_position_controller:
  joint: LFJ0
  pid:
    d: 0.005
    i: 0.1
    i_clamp: 0.05
    p: 0.5
    position_deadband: 0.0
    friction_deadband: 0.0
    max_force: 1.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_lfj3_position_controller:
  joint: LFJ3
  pid:
    d: 0.05
    i: 0.2
    i_clamp: 0.2
    p: 1.0
    position_deadband: 0.0
    friction_deadband: 0.0
    max_force: 1.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_lfj4_position_controller:
  joint: LFJ4
  pid:
    d: 0.05
    i: 0.2
    i_clamp: 0.2
    p: 1.0
    position_deadband: 0.0
    friction_deadband: 0.0
    max_force: 1.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_lfj5_position_controller:
  joint: LFJ5
  pid:
    d: 0.05
    i: 0.2
    i_clamp: 0.2
    p: 1.0
    position_deadband: 0.0
    friction_deadband: 0.0
    max_force: 1.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_mfj0_position_controller:
  joint: MFJ0
  pid:
    d: 0.005
    i: 0.1
    i_clamp: 0.05
    p: 0.5
    position_deadband: 0.0
    friction_deadband: 0.0
    max_force: 1.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_mfj3_position_controller:
  joint: MFJ3
  pid:
    d: 0.05
    i: 0.2
    i_clamp: 0.2
    p: 1.0
    position_deadband: 0.0
    friction_deadband: 0.0
    max_force: 1.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_mfj4_position_controller:
  joint: MFJ4
  pid:
    d: 0.05
    i: 0.2
    i_clamp: 0.2
    p: 1.0
    position_deadband: 0.0
    friction_deadband: 0.0
    max_force: 1.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rfj0_position_controller:
  joint: RFJ0
  pid:
    d: 0.005
    i: 0.1
    i_clamp: 0.05
    p: 0.5
    position_deadband: 0.0
    friction_deadband: 0.0
    max_force: 1.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rfj3_position_controller:
  joint: RFJ3
  pid:
    d: 0.05
    i: 0.2
    i_clamp: 0.2
    p: 1.0
    position_deadband: 0.0
    friction_deadband: 0.0
    max_force: 1.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rfj4_position_controller:
  joint: RFJ4
  pid:
    d: 0.05
    i: 0.2
    i_clamp: 0.2
    p: 1.0
    position_deadband: 0.0
    friction_deadband: 0.0
    max_force: 1.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_thj1_position_controller:
  joint: THJ1
  pid:
    d: 0.0
    i: 0.2
    i_clamp: 0.2
    p: 1.0
    position_deadband: 0.0
    friction_deadband: 0.0
    max_force: 1.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_thj2_position_controller:
  joint: THJ2
  pid:
    d: 0.0
    i: 0.7
    i_clamp: 0.4
    p: 1.5
    position_deadband: 0.0
    friction_deadband: 0.0
    max_force: 1.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_thj3_position_controller:
  joint: THJ3
  pid:
    d: 0.0
    i: 0.2
    i_clamp: 0.2
    p: 0.5
    position_deadband: 0.0
    friction_deadband: 0.0
    max_force: 1.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_thj4_position_controller:
  joint: THJ4
  pid:
    d: 0.0
    i: 0.4
    i_clamp: 0.3
    p: 1.0
    position_deadband: 0.0
    friction_deadband: 0.0
    max_force: 2.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_thj5_position_controller:
  joint: THJ5
  pid:
    d: 0.05
    i: 0.1
    i_clamp: 0.4
    p: 0.4
    position_deadband: 0.0
    friction_deadband: 0.0
    max_force: 3.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_wrj1_position_controller:
  joint: WRJ1
  pid:
    d: 1.0
    i: 1.5
    i_clamp: 0.8
    p: 10.0
    position_deadband: 0.0
    friction_deadband: 0.0
    max_force: 5.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_wrj2_position_controller:
  joint: WRJ2
  pid:
    d: 0.2
    i: 1.5
    i_clamp: 0.5
    p: 8.0
    position_deadband: 0.0
    friction_deadband: 0.0
    max_force: 10.0
  type: sr_mechanism_controllers/SrhJointPositionController
