controller_list:
  - name: ra_lwr_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints: 
      - ra_0_joint
      - ra_1_joint
      - ra_2_joint
      - ra_3_joint
      - ra_4_joint
      - ra_5_joint
      - ra_6_joint
