#!/usr/bin/env python

from main_window import MainWindow
from PyQt4 import QtGui
import sys, os

def main():
    """
    Starts the GUI.
    """
    app = QtGui.QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec_())

if __name__ == "__main__":
    main()
