# Copyright 2022 Shadow Robot Company Ltd.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation version 2 of the License.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

version: 2
jobs:
  build:
    working_directory: /tmp/repository
    docker:
      - image: public.ecr.aws/shadowrobot/build-tools:focal-noetic
        environment:
          toolset_branch: lint
          server_type: circle
          ros_release_name: noetic
          ubuntu_version_name: focal
          used_modules: check_cache,code_style_check
    steps:
      - checkout
      - run: echo 'export remote_shell_script="https://raw.githubusercontent.com/shadow-robot/sr-build-tools/$toolset_branch/bin/sr-run-ci-build.sh"' >> $BASH_ENV
      - run: wget -O /tmp/oneliner "$( echo "$remote_shell_script" | sed 's/#/%23/g' )"
      - run: chown -R $MY_USERNAME:$MY_USERNAME $CIRCLE_WORKING_DIRECTORY
      - run: chmod 755 /tmp/oneliner
      - run: gosu $MY_USERNAME /tmp/oneliner "$toolset_branch" $server_type $used_modules

      - store_test_results:
          path: test_results

      - store_artifacts:
          path: code_coverage_results
