joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 300  

ra_lwr_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  topic: "ra_lwr_trajectory_controller"
  joints:
     - ra_0_joint
     - ra_1_joint
     - ra_2_joint
     - ra_3_joint
     - ra_4_joint
     - ra_5_joint
     - ra_6_joint
  gains:
    ra_0_joint: {p: 500.0, i: 70.0, d: 10.0, i_clamp: 2500.0}
    ra_1_joint: {p: 900.0, i: 150.0, d: 10.0, i_clamp: 2500.0}
    ra_2_joint: {p: 500.0, i: 70.0, d: 10.0, i_clamp: 2500.0}
    ra_3_joint: {p: 900.0, i: 150.0, d: 10.0, i_clamp: 2500.0}
    ra_4_joint: {p: 500.0, i: 70.0, d: 10.0, i_clamp: 2500.0}
    ra_5_joint: {p: 900.0, i: 150.0, d: 10.0, i_clamp: 2500.0}
    ra_6_joint: {p: 500.0, i: 70.0, d: 10.0, i_clamp: 2500.0}

  state_publish_rate:  25
  action_monitor_rate: 10
